name = "CoOptimalTransport"
uuid = "f7d695e8-ed74-4184-9a42-69439e50cb1a"
authors = ["Stephen Zhang <syz@syz.id.au>"]
version = "0.1.0"

[deps]
OptimalTransport = "7e02d93a-ae51-4f58-b602-d97af76e3b33"
